
# ENV
alpha: 0.60
rank_path: './preprocess_data/geolife/rank_list.npy'
track_path: './dataset/geolife/real.data'
max_closest_rank: 200
traj_length: 48

# Sensitivity module parameters
use_adaptive_privacy: true
min_sensitivity: 0.01
sensitivity_scaling: 1.0


# PPO
episode: 150
capacity: 1000
gamma: 0.99
lam: 0.95
value_learning_rate: 0.0003
policy_learning_rate: 0.0003
discriminator_learning_rate: 0.0003
batch_size: 50
policy_iter: 1
disc_iter: 10
value_iter: 1
epsilon: 0.2
entropy_weight: 0.001
train_iter: 100
clip_grad: 10

# ATNetwork
total_locations: 4210
time_scale: 48
loc_embedding_dim: 32
tim_embedding_dim: 8
hidden_dim: 64
bidirectional: False
device: 0
data: 'geolife'
starting_sample: 'zero'
starting_dist: null
embedding_net: null

# Recover_CNN
act_embedding_dim: 4
recover_cnn_reward_ratio: 0.5
recover_cnn_learning_rate: 0.0003

model_save_interval: 10
test_data_path: './dataset/geolife/test.data'


# # ENV
# alpha: 0.60
# rank_path: './preprocess_data/geolife/rank_list.npy'
# track_path: './dataset/geolife/real.data'
# max_closest_rank: 200
# traj_length: 48

# # Sensitivity module parameters
# use_adaptive_privacy: true
# min_sensitivity: 0.01
# sensitivity_scaling: 1.0

# # PPO - Adjusted for DP stability
# episode: 10000  # Increased from 150 for better convergence
# capacity: 1000
# gamma: 0.99
# lam: 0.95
# value_learning_rate: 0.0001      # Reduced from 0.0003
# policy_learning_rate: 0.0001     # Reduced from 0.0003
# discriminator_learning_rate: 0.0003
# batch_size: 50
# policy_iter: 1
# disc_iter: 5                     # Reduced from 10 for stability
# value_iter: 1
# epsilon: 0.2
# entropy_weight: 0.01             # Increased from 0.001 for exploration
# train_iter: 100
# clip_grad: 1.0                   # Reduced from 10 for tighter control

# # ATNetwork
# total_locations: 4210
# time_scale: 48
# loc_embedding_dim: 32
# tim_embedding_dim: 8
# hidden_dim: 64
# bidirectional: False
# device: 0
# data: 'geolife'
# starting_sample: 'zero'
# starting_dist: null
# embedding_net: null

# # Recover_CNN
# act_embedding_dim: 4
# recover_cnn_reward_ratio: 0.5
# recover_cnn_learning_rate: 0.0003

# model_save_interval: 10
# test_data_path: './dataset/geolife/test.data'

# # Additional DP-specific parameters (optional)
# dp_warm_up_episodes: 1000        # Episodes before full noise
# dp_eval_frequency: 500           # Evaluate every N episodes
# dp_checkpoint_frequency: 1000    # Save checkpoints every N episodes